name: Check Notice

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install -r requirements.txt

    - run: python check.py

    - name: Commit state
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add last.txt
        git commit -m "update" || exit 0
        git push
